/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:901739:
  appc.background(230);
} //_CODE_:window1:901739:

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:342012:
  println("panel2 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:342012:

public void addImageButton_click(GButton source, GEvent event) { //_CODE_:addImageButton:429372:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  selectInput("Select image file", "onImageFileSelected"); 
} //_CODE_:addImageButton:429372:

public void imageScaleSldier_change(GSlider source, GEvent event) { //_CODE_:imageScaleSlider:344463:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
  float val = source.getValueF();
  imageManager.setScale(val);
} //_CODE_:imageScaleSlider:344463:

public void exitButton_click(GButton source, GEvent event) { //_CODE_:exitButton:885400:
  println("exitButton - GButton >> GEvent." + event + " @ " + millis());
  exitRequested = true;
 
} //_CODE_:exitButton:885400:

public void fullscreenButton_click(GButton source, GEvent event) { //_CODE_:fullscreenButton:709525:
  println("fullscreenButton - GButton >> GEvent." + event + " @ " + millis());
  fullScreen();
} //_CODE_:fullscreenButton:709525:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(true);
  G4P.setGlobalColorScheme(GCScheme.GREEN_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Properties", 0, 0, 300, 200, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.CLOSE_WINDOW);
  window1.addDrawHandler(this, "win_draw1");
  panel1 = new GPanel(window1, 10, 10, 280, 180, "Configuration");
  panel1.setText("Configuration");
  panel1.setTextBold();
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  addImageButton = new GButton(window1, 100, 40, 80, 30);
  addImageButton.setText("Add image ...");
  addImageButton.addEventHandler(this, "addImageButton_click");
  imageScaleSlider = new GSlider(window1, 21, 82, 225, 50, 10.0);
  imageScaleSlider.setShowValue(true);
  imageScaleSlider.setShowLimits(true);
  imageScaleSlider.setLimits(1.0, 0.0, 4.0);
  imageScaleSlider.setNbrTicks(10);
  imageScaleSlider.setStickToTicks(true);
  imageScaleSlider.setShowTicks(true);
  imageScaleSlider.setNumberFormat(G4P.DECIMAL, 2);
  imageScaleSlider.setOpaque(false);
  imageScaleSlider.addEventHandler(this, "imageScaleSldier_change");
  exitButton = new GButton(window1, 20, 139, 80, 30);
  exitButton.setText("Exit");
  exitButton.setTextBold();
  exitButton.addEventHandler(this, "exitButton_click");
  fullscreenButton = new GButton(window1, 110, 139, 80, 30);
  fullscreenButton.setText("Full screen");
  fullscreenButton.setTextItalic();
  fullscreenButton.addEventHandler(this, "fullscreenButton_click");
  panel1.addControl(addImageButton);
  panel1.addControl(imageScaleSlider);
  panel1.addControl(exitButton);
  panel1.addControl(fullscreenButton);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GPanel panel1; 
GButton addImageButton; 
GSlider imageScaleSlider; 
GButton exitButton; 
GButton fullscreenButton; 